version: "2"
services:
  bootstrap:
    image: bhgedigital/envsubst
    container_name: mocknet_bootstrap
    working_dir: /srv
    volumes:
      - ./:/srv
    command: sh -c "./setup.sh"
    networks:
      - mocknet
  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: ${POSTGRES_NAME}
    restart: on-failure
    # cpus: ${POSTGRES_CPU}
    # mem_reservation: ${POSTGRES_MEM}
    volumes:
      - ${POSTGRES_SETUP}:/docker-entrypoint-initdb.d/stacks-node-api.sql
    ports:
      - ${POSTGRES_PORT_LOCAL}:${POSTGRES_PORT}
    expose:
      - ${POSTGRES_PORT}
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - mocknet
    depends_on:
      - bootstrap
  miner:
    image: ${STACKS_IMAGE}
    container_name: ${STACKS_MINER_NAME}
    restart: on-failure
    # cpus: ${STACKS_MINER_CPU}
    # mem_reservation: ${STACKS_MINER_MEM}
    volumes:
      - ${STACKS_MINER_CONFIG}:/src/stacks-node/Config.toml
    ports:
      - ${STACKS_MINER_RPC_PORT_LOCAL}:${STACKS_MINER_RPC_PORT}
      - ${STACKS_MINER_P2P_PORT_LOCAL}:${STACKS_MINER_P2P_PORT}
    expose:
      - ${STACKS_MINER_RPC_PORT}
      - ${STACKS_MINER_P2P_PORT}
    networks:
      - mocknet
    depends_on:
      - bootstrap
    command: /bin/stacks-node start --config /src/stacks-node/Config.toml
  follower:
    image: ${STACKS_IMAGE}
    container_name: ${STACKS_FOLLOWER_NAME}
    restart: on-failure
    # cpus: ${STACKS_FOLLOWER_CPU}
    # mem_reservation: ${STACKS_FOLLOWER_MEM}
    volumes:
      - ${STACKS_FOLLOWER_CONFIG}:/src/stacks-node/Config.toml
    expose:
      - ${STACKS_FOLLOWER_RPC_PORT}
      - ${STACKS_FOLLOWER_P2P_PORT}
    networks:
      - mocknet
    depends_on:
      - miner
      - api
    command: /bin/stacks-node start --config /src/stacks-node/Config.toml
  api:
    image: ${API_IMAGE}
    container_name: ${API_NAME}
    restart: on-failure
    # cpus: ${API_CPU}
    # mem_reservation: ${API_MEM}
    ports:
      - ${API_STACKS_CORE_EVENT_PORT_LOCAL}:${API_STACKS_CORE_EVENT_PORT}
      - ${API_STACKS_BLOCKCHAIN_API_PORT_LOCAL}:${API_STACKS_BLOCKCHAIN_API_PORT}
    expose:
      - ${API_STACKS_CORE_EVENT_PORT}
      - ${API_STACKS_BLOCKCHAIN_API_PORT}
    environment:
      - NODE_ENV=${API_NODE_ENV}
      - GIT_TAG=${API_GIT_TAG}
      - PG_HOST=${POSTGRES_NAME}.mocknet
      - PG_PORT=${POSTGRES_PORT_LOCAL}
      - PG_USER=${API_PG_USER}
      - PG_PASSWORD=${POSTGRES_PASSWORD}
      - PG_DATABASE=${API_PG_DATABASE}
      - PG_SCHEMA=${API_PG_SCHEMA}
      - STACKS_CHAIN_ID=${API_STACKS_CHAIN_ID}
      - V2_POX_MIN_AMOUNT_USTX=${API_V2_POX_MIN_AMOUNT_USTX}
      - STACKS_CORE_EVENT_PORT=${API_STACKS_CORE_EVENT_PORT}
      - STACKS_CORE_EVENT_HOST=${API_STACKS_CORE_EVENT_HOST}
      - STACKS_BLOCKCHAIN_API_PORT=${API_STACKS_BLOCKCHAIN_API_PORT}
      - STACKS_BLOCKCHAIN_API_HOST=${API_STACKS_BLOCKCHAIN_API_HOST}
      - STACKS_BLOCKCHAIN_API_DB=${API_STACKS_BLOCKCHAIN_API_DB}
      - STACKS_CORE_RPC_HOST=${STACKS_FOLLOWER_NAME}.mocknet
      - STACKS_CORE_RPC_PORT=${STACKS_FOLLOWER_RPC_PORT}
      - BTC_FAUCET_PK=${BTC_FAUCET_PK}
      - BTC_RPC_PORT=${BTC_RPC_PORT}
      - BTC_RPC_HOST=http://${BTC_NAME}.mocknet
      - BTC_RPC_PW=${BTC_PW}
      - BTC_RPC_USER=${BTC_USER}
    networks:
      - mocknet
    depends_on:
      - postgres
networks:
  mocknet:
    driver: bridge
    name: mocknet