version: '3'
services:
  alpine:
    image: alpine
    container_name: bns_data
    working_dir: /srv
    volumes:
      - ../persistent-data/bns-data:/bns-data
      - ../scripts:/scripts
    env_file:
      - ../.env
    command: sh -c "/scripts/setup-bns.sh"