version: "3"
services:
  alpine:
    image: alpine
    container_name: bns_data
    working_dir: /srv
    volumes:
      - ${SCRIPTPATH}/persistent-data/bns-data:/bns-data
      - ${SCRIPTPATH}/scripts:/scripts
    env_file:
      - ${SCRIPTPATH}/.env
    networks:
      - stacks-blockchain
    profiles:
      - bns
    command: sh -c "/scripts/setup-bns.sh"
networks:
  stacks-blockchain:
    driver: bridge
    name: stacks
