version: "3"
services:
  stacks-node-follower:
    image: blockstack/stacks-blockchain:feat-miner-control
    volumes:
      - ./private-testnet:/src/stacks-node
  bitcoin:
    image: blockstack/bitcoind:puppet-chain
    container_name: bitcoin
    restart: on-failure
    volumes:
      - ./private-testnet:/etc/bitcoin
    expose:
      - 18443
      - 28444
    environment:
      - DYNAMIC_GENESIS_TIMESTAMP=1
      - RUST_BACKTRACE=1
    networks:
      - stacks-blockchain
