version: "3"
services:
  stacks-node-follower:
    volumes:
      - ./private-testnet:/src/stacks-node
  bitcoin:
    image: blockstack/bitcoind:puppet-chain
    container_name: bitcoin
    restart: on-failure
    volumes:
      - ./private-testnet:/etc/bitcoin
    ports:
      - 18332:18332
      - 18333:18333
    environment:
      - DYNAMIC_GENESIS_TIMESTAMP=1
      - RUST_BACKTRACE=1
    networks:
      - stacks-blockchain